#!/bin/sh
for i in 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010
do
cd Input
sed s/YEAR/$i/g create.tmp > create
./create
cd ..
./cam2wrf.exe
cd Output
sed s/YEAR/$i/g move.tmp > move
./move
cd ..
done
